require("uladzislau.core.options")
require("uladzislau.core.colorscheme")
require("uladzislau.core.keymaps")

require("uladzislau.plugins-setup")
require("uladzislau.plugins.comment")
require("uladzislau.plugins.nvim-tree")
require("uladzislau.plugins.lualine")
require("uladzislau.plugins.telescope")
require("uladzislau.plugins.nvim-cmp")
require("uladzislau.plugins.lsp.mason")
require("uladzislau.plugins.lsp.lspconfig")
require("uladzislau.plugins.lsp.lspsaga")
require("uladzislau.plugins.lsp.none-ls")
require("uladzislau.plugins.autopairs")
require("uladzislau.plugins.treesitter")
require("uladzislau.plugins.gitsigns")
